export const GET_SHIPMENTS = "GET_SHIPMENTS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const SET_LOADING = "SET_LOADING";
export const SHIPMENT_ERROR = "SHIPMENT_ERROR";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_BIKERS = "GET_BIKERS";
